# Generated by Django 5.1.1 on 2024-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_name_teacher_first_name_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
