# Generated by Django 5.1.1 on 2024-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='id',
        ),
        migrations.AddField(
            model_name='trainers',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainers',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
