# Generated by Django 5.1.1 on 2024-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.PositiveSmallIntegerField()),
                ('module_id', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=20)),
                ('date_created', models.EmailField(max_length=254)),
                ('total_marks', models.CharField()),
                ('assessment_duration', models.DateTimeField()),
            ],
        ),
    ]
