# Generated by Django 5.1.1 on 2024-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='kicd_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='teachers_grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='teachers_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
