# Generated by Django 5.1.1 on 2024-09-17 08:52

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='department',
        ),
        migrations.RemoveField(
            model_name='module',
            name='email',
        ),
        migrations.RemoveField(
            model_name='module',
            name='kicd_id',
        ),
        migrations.AddField(
            model_name='module',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='module',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='module',
            name='total_marks',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='module',
            name='trainer_id',
            field=models.IntegerField(),
        ),
    ]
