# Generated by Django 5.1.1 on 2024-09-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_department_remove_module_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
