# Generated by Django 5.1.1 on 2024-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking_scheme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markingscheme',
            name='id',
        ),
        migrations.AlterField(
            model_name='markingscheme',
            name='markingscheme_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='markingscheme',
            name='module_id',
            field=models.IntegerField(),
        ),
    ]
