# Generated by Django 5.1.1 on 2024-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking_scheme', '0002_remove_markingscheme_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markingscheme',
            name='name',
        ),
        migrations.AddField(
            model_name='markingscheme',
            name='module_name',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='markingscheme',
            name='date_created',
            field=models.DateField(),
        ),
    ]
