# Generated by Django 5.1.1 on 2024-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KICD', '0002_rename_name_kicd_first_name_remove_kicd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicd',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
